// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nifty50.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nifty50.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nifty50.Core.Entities.Dividend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Dividends");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.FinancialStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AccountsPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AccountsReceivable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CapitalExpenditures")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CashAndEquivalents")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CostOfRevenue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CurrentLiabilities")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DilutedEPS")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DividendsPaid")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EBITDA")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EarningsPerShare")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FreeCashFlow")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GrossProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InterestExpense")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Inventory")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("NetDebt")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OperatingCashFlow")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OperatingExpenses")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OperatingIncome")
                        .HasColumnType("numeric");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ShareRepurchases")
                        .HasColumnType("numeric");

                    b.Property<int>("StatementType")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TaxProvision")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalDebt")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalEquity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalLiabilities")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "StatementType", "Period", "PeriodEndDate")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("FinancialStatements");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.FundamentalMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AssetTurnover")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BookValuePerShare")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CashRatio")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DebtToAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DebtToEquity")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DividendPayoutRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EPS")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EVToEBITDA")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EVToFCF")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EarningsGrowthYoY")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FCFGrowthYoY")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FreeCashFlowPerShare")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GrossProfitMargin")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InterestCoverageRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InventoryTurnover")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("NetProfitMargin")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OperatingMargin")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PBRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PEGRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PERatio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PSRatio")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("QuickRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ROA")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ROE")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ROIC")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ReceivablesTurnover")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RevenueGrowthYoY")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "PeriodEndDate")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("FundamentalMetrics");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.ScoringProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlertMinFundamentalScore")
                        .HasColumnType("integer");

                    b.Property<int>("AlertMinOverallScore")
                        .HasColumnType("integer");

                    b.Property<int>("AlertMinSentimentScore")
                        .HasColumnType("integer");

                    b.Property<int>("AlertMinTechnicalScore")
                        .HasColumnType("integer");

                    b.Property<int>("BuyThreshold")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DividendWeight")
                        .HasColumnType("integer");

                    b.Property<int>("FundGrowthWeight")
                        .HasColumnType("integer");

                    b.Property<int>("FundLeverageWeight")
                        .HasColumnType("integer");

                    b.Property<int>("FundLiquidityWeight")
                        .HasColumnType("integer");

                    b.Property<int>("FundProfitabilityWeight")
                        .HasColumnType("integer");

                    b.Property<int>("FundValuationWeight")
                        .HasColumnType("integer");

                    b.Property<int>("FundamentalWeight")
                        .HasColumnType("integer");

                    b.Property<int>("HoldThreshold")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPreset")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SellThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("SentimentWeight")
                        .HasColumnType("integer");

                    b.Property<int>("StrongBuyThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("TechADXWeight")
                        .HasColumnType("integer");

                    b.Property<int>("TechBollingerWeight")
                        .HasColumnType("integer");

                    b.Property<int>("TechMACDWeight")
                        .HasColumnType("integer");

                    b.Property<int>("TechMovingAvgWeight")
                        .HasColumnType("integer");

                    b.Property<int>("TechRSIWeight")
                        .HasColumnType("integer");

                    b.Property<int>("TechVolumeWeight")
                        .HasColumnType("integer");

                    b.Property<int>("TechnicalWeight")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("ScoringProfiles");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.SentimentAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("NegativeCount")
                        .HasColumnType("integer");

                    b.Property<int>("NeutralCount")
                        .HasColumnType("integer");

                    b.Property<int>("OverallSentiment")
                        .HasColumnType("integer");

                    b.Property<int>("PositiveCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("SentimentScore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<string>("TopHeadlines")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "AnalyzedAt")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("SentimentAnalyses");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DayChange")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DayChangePercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("numeric");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Week52High")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Week52Low")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.StockAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlertMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DividendScore")
                        .HasColumnType("integer");

                    b.Property<int>("FundamentalScore")
                        .HasColumnType("integer");

                    b.Property<int>("FundamentalSignal")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAlert")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<int>("OverallSignal")
                        .HasColumnType("integer");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text");

                    b.Property<Guid>("ScoringProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("SentimentScore")
                        .HasColumnType("integer");

                    b.Property<int>("SentimentSignal")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<int>("TechnicalScore")
                        .HasColumnType("integer");

                    b.Property<int>("TechnicalSignal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeightsUsed")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ScoringProfileId");

                    b.HasIndex("StockId", "AnalyzedAt")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("StockAnalyses");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.StockPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdjClose")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "Date")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("StockPrices");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.TechnicalIndicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ADX14")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ATR14")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BollingerLower")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BollingerMiddle")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BollingerUpper")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CCI20")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EMA12")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EMA26")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IchimokuKijun")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IchimokuSenkouA")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IchimokuSenkouB")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IchimokuTenkan")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MACD")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MACDHistogram")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MACDSignal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MFI14")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OBV")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ParabolicSar")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RSI14")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SMA20")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SMA200")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SMA50")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StochD")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StochK")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("VWAP")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WilliamsR14")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "Date")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("TechnicalIndicators");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.Dividend", b =>
                {
                    b.HasOne("Nifty50.Core.Entities.Stock", "Stock")
                        .WithMany("Dividends")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.FinancialStatement", b =>
                {
                    b.HasOne("Nifty50.Core.Entities.Stock", "Stock")
                        .WithMany("FinancialStatements")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.FundamentalMetric", b =>
                {
                    b.HasOne("Nifty50.Core.Entities.Stock", "Stock")
                        .WithMany("FundamentalMetrics")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.SentimentAnalysis", b =>
                {
                    b.HasOne("Nifty50.Core.Entities.Stock", "Stock")
                        .WithMany("SentimentAnalyses")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.StockAnalysis", b =>
                {
                    b.HasOne("Nifty50.Core.Entities.ScoringProfile", "ScoringProfile")
                        .WithMany("StockAnalyses")
                        .HasForeignKey("ScoringProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nifty50.Core.Entities.Stock", "Stock")
                        .WithMany("StockAnalyses")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringProfile");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.StockPrice", b =>
                {
                    b.HasOne("Nifty50.Core.Entities.Stock", "Stock")
                        .WithMany("Prices")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.TechnicalIndicator", b =>
                {
                    b.HasOne("Nifty50.Core.Entities.Stock", "Stock")
                        .WithMany("TechnicalIndicators")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.ScoringProfile", b =>
                {
                    b.Navigation("StockAnalyses");
                });

            modelBuilder.Entity("Nifty50.Core.Entities.Stock", b =>
                {
                    b.Navigation("Dividends");

                    b.Navigation("FinancialStatements");

                    b.Navigation("FundamentalMetrics");

                    b.Navigation("Prices");

                    b.Navigation("SentimentAnalyses");

                    b.Navigation("StockAnalyses");

                    b.Navigation("TechnicalIndicators");
                });
#pragma warning restore 612, 618
        }
    }
}
